apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:kJySweS0hEAZAnapJndAQeou5b4ctZadzg==,iv:CW1acK/LF6S5wU0ovrhb5RFdbUmyiMHcJekRHxI29as=,tag:7UlWhoqLKbcnBcTtXg8epw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-27T12:40:42Z"
    mac: ENC[AES256_GCM,data:Py7jDTHQue2mwnQVNpMVvDXBRMRrVvEcLh73Wsl/lvXADrd9yWavqLTbrrpJ3FALYNi46Ax3mD1S5D1eka5fQIvPCSkeayGMfgN5N++fBUxZ7nfvY0ZOjpKnDX41bKpnGglf4oKbFpZU1XPKWidQ1YdNgI4dPqyPdoUMBRFnSQ4=,iv:QmGj57vwSXDlaec6fGy02EdMDvWojBgdIpBDtmCLSi0=,tag:xaJ2gfVcKUymL6tctzMFPg==,type:str]
    pgp:
        - created_at: "2023-06-27T12:40:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxGk+c2h9vP5AQv/bzPyhVGXpVJt+7X2ftv25Rn7JTG3WTRUyaW/yYbh4q9S
            3NvjgCvi1xvV1RVqai3mVl0Zuoth4L4YL+XAwffKnsiP5o1Mf40uGlQLROm1KnD4
            pQNf2ChoMtg/xiJl6myA59IphH3lkJg4fuEvLgB+zVPcC7KJ7dDaP9IXwfTD9E3v
            iHJAFnlmXmePqiW1LWMuVfvMAgn7Ek1lz4FUXLEFpKNVjgpm/TDBAm9GmHBGYoER
            amjt3AWRokOhJtly3xD/uuhPZcUTt4ljXc0+qupYh/vkW3QXaxNLAlfX1k+THcDI
            rsw88QeBuUvoCAZZOooD5oebCUphuzCrMYZRXsEn5EMDI/MbFgnSOBvVt1ChV7DV
            4QKfM8v6BOb+S09lG/Ewaeg/mOj/FZiCH/cILiCXOdtpmMkP5e5oljJbeTrSETgh
            CdQvI9L9dcO48+X2+yhDS0tH+OWYkmWEcPN6rXFGNaUXTYv2FkRRT05naZUfFk0q
            AxO4osCreVTGSh1fHCwW0l4BZ/le3OXGtrFjHgdnmnEzdMFvXr+tQyT4sd1WfWK9
            GitCuixfoL5sKDNrySy5ns30PFBjcjS7QbtkQOcc7Hp+ulP0KGcJqgDcl5SmTFc4
            Xsk/8e52T9q9wEgD31Ey
            =JByh
            -----END PGP MESSAGE-----
          fp: EBA4253752830EEA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
